version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379

  ingress:
    depends_on:
      - mongodb
      - redis
    build: ./ingress
    ports:
      - 8084:8084
    links:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/angler
      - REDIS_URI=redis://redis:6379/0

  geoip-api:
    depends_on:
      - mongodb
      - redis
    build: ./geoip-api
    links:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/angler
      - REDIS_URI=redis://redis:6379/0

  #frontend:
  #  build: ./web
  #  ports:
  #    - 3000:3000
    #links:
    #  - backend

  # backend

  # auth

  # mailer

volumes:
  mongodb_data:
