version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379

  ingress:
    depends_on:
      - mongodb
      - redis
    image: ghcr.io/konstfish/angler_ingress:latest
    ports:
      - 8084:8084
    links:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/angler
      - REDIS_URI=redis://redis:6379/0
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4318

  geoip-api:
    depends_on:
      - mongodb
      - redis
    image: ghcr.io/konstfish/angler_geoip-api:latest
    links:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/angler
      - REDIS_URI=redis://redis:6379/0
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4318

  auth:
    depends_on:
      - mongodb
      - redis
    image: ghcr.io/konstfish/angler_auth:latest
    links:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/angler
      - REDIS_URI=redis://redis:6379/0
      - JWT_SECRET=secret
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4318

  backend:
    depends_on:
      - mongodb
      - redis
    image: ghcr.io/konstfish/angler_backend:latest
    links:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/angler
      - REDIS_URI=redis://redis:6379/0
      - AUTH_URL=http://auth:8086/api/auth/v1/verify
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4318

  frontend:
    image: ghcr.io/konstfish/angler_frontend:latest

  router:
    build: ./helper/router
    ports:
      - 3000:3000
    links:
      - frontend
      - auth
      - backend
      - ingress

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686

  # mailer

volumes:
  mongodb_data:
