version: '3.7'
services:
  frontend:
    build: ./frontend
    image: ghcr.io/konstfish/angler_frontend:latest

  ingress:
    build:
      context: .
      dockerfile: helper/docker/Dockerfile.gowork
      args:
        - COMPONENT=ingress
    image: ghcr.io/konstfish/angler_ingress:latest

  geoip-api:
    build:
      context: .
      dockerfile: helper/docker/Dockerfile.goworkinit
      args:
        - COMPONENT=geoip-api
    image: ghcr.io/konstfish/angler_geoip-api:latest

  backend:
    build:
      context: .
      dockerfile: helper/docker/Dockerfile.gowork
      args:
        - COMPONENT=backend
    image: ghcr.io/konstfish/angler_backend:latest
  
  auth:
    build:
      context: .
      dockerfile: helper/docker/Dockerfile.gowork
      args:
        - COMPONENT=auth
    image: ghcr.io/konstfish/angler_auth:latest

  router:
    build: ./helper/router