version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  # redis

  ingress:
    depends_on:
      - mongodb
    build: ./ingress
    ports:
      - 8084:8084
    links:
      - mongodb

  frontend:
    depends_on:
      - mongodb
    build: ./web
    ports:
      - 3000:3000
    #links:
    #  - backend

  # backend

  # auth

  # mailer

volumes:
  mongodb_data:
