version: '3.7'
services:
  frontend:
    build: ./frontend
    image: ghcr.io/konstfish/angler_frontend:latest

  ingress:
    build:
      context: .
      dockerfile: ingress/Dockerfile.local
    image: ghcr.io/konstfish/angler_ingress:latest

  geoip-api:
    build:
      context: .
      dockerfile: geoip-api/Dockerfile.local
    image: ghcr.io/konstfish/angler_geoip-api:latest

  backend:
    build: ./backend
    image: ghcr.io/konstfish/angler_backend:latest
  
  auth:
    build: ./auth
    image: ghcr.io/konstfish/angler_auth:latest

  router:
    build: ./router