version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379

  ingress:
    depends_on:
      - mongodb
      - redis
    image: ghcr.io/konstfish/angler_ingress:latest
    ports:
      - 8084:8084
    links:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/angler
      - REDIS_URI=redis://redis:6379/0

  geoip-api:
    depends_on:
      - mongodb
      - redis
    image: ghcr.io/konstfish/angler_geoip-api:latest
    links:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/angler
      - REDIS_URI=redis://redis:6379/0
    
  auth:
    depends_on:
      - mongodb
      - redis
    build: ./auth
    links:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/angler
      - REDIS_URI=redis://redis:6379/0
  
  backend:
    depends_on:
      - mongodb
      - redis
    build: ./backend
    links:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/angler
      - REDIS_URI=redis://redis:6379/0

  frontend:
    image: ghcr.io/konstfish/angler_frontend:latest

  router:
    build: ./helper/router
    ports:
      - 3000:3000
    links:
      - frontend
      - auth
      - backend
      - ingress

  # mailer

volumes:
  mongodb_data:
