apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: angler-mongo
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  prometheus:
    username: prometheus-username
    passwordSecretRef:
      name: metrics-endpoint-password
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: angler-user
      db: admin
      passwordSecretRef:
        name: angler-mongo-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: angler-mongo-scram
--- 
apiVersion: v1
kind: Secret
metadata:
  name: angler-mongo-user-password
  namespace: mongodb
type: Opaque
stringData:
  password: asdf1234asdfsmile
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-endpoint-password
  namespace: mongodb
type: Opaque
stringData:
  password: 'Not-So-Secure!'
  username: prometheus-username
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:  
  labels:
    app: angler-mongo-svc
    release: prometheus-stack
  name: angler-mongo-sm
  namespace: mongodb
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: metrics-endpoint-password
      username:
        key: username
        name: metrics-endpoint-password

    port: prometheus
    scheme: http
  namespaceSelector:
    matchNames:
    - mongodb
  selector:
    matchLabels:
      app: angler-mongo-svc