apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: angler-mongo
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: angler-user
      db: admin
      passwordSecretRef:
        name: angler-mongo-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: angler-mongo-scram
--- 
apiVersion: v1
kind: Secret
metadata:
  name: angler-mongo-user-password
  namespace: mongodb
type: Opaque
stringData:
  password: asdf1234asdfsmile