name: Build

on:
  push:
    branches:
      - '*'

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [frontend, ingress, geoip-api]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: docker-practice/actions-setup-docker@master

      - name: Build
        run: |
          cd ${{ matrix.component }}
          docker build -t angler_${{ matrix.component }} .
          